server:
  port: 8000

spring:
  main:
    allow-bean-definition-overriding : true
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username : root
    password : ireIRE@1004
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  application:
    name: user-service


eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
greeting:
  message: welcome to the simple e-commerce
